version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: dependency
          command: npm install
      - run:
          name: build
          command: |
            npm run bower
            npm run build
      - add_ssh_keys:
          fingerprints:
            - "ce:d2:65:09:3b:c4:1a:c6:5f:31:6f:a5:e1:7f:ab:a6"
      - deploy:
          name: deploy to server
          command: |
            scp -r dist/${DEPLOY_YEAR} ${SSH_USER}@${HOST_NAME}:${DEPLOY_DIR}/www 
