version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: dependency
          command: npm install
      - run:
          name: build
          command: |
            npm run bower
            npm run build
      - add_ssh_keys:
          fingerprints:
            - "56:59:a1:83:5c:8a:c0:1a:e8:a7:8d:c9:d3:56:54:6c"
      - deploy:
          name: deploy to server
          command: |
            scp -r dist/${DEPLOY_YEAR} ${SSH_USER}@${HOST_NAME}:${DEPLOY_DIR}/www 
