<!DOCTYPE HTML>
<html>

<head>
	<title>保土ヶ谷宿場まつり{{ year }}</title>
	<meta content="JavaScript" name="vs_defaultClientScript">
	<meta content="http://schemas.microsoft.com/intellisense/ie5" name="vs_targetSchema">
	<meta charset="UTF-8">
	<link href="css/main.css" type="text/css" rel="stylesheet">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- bower:css -->
  <!-- endbower -->
</head>

<body>

{% block content %}{% endblock %}

	<footer>
		Copyright &copy; 2016 保土ヶ谷宿場まつり実行委員会 All Rights Reserved.
	</footer>
	  <!-- bower:js -->
	  <!-- endbower -->
	<script>
		(function(i, s, o, g, r, a, m) {
			i['GoogleAnalyticsObject'] = r;
			i[r] = i[r] || function() {
				(i[r].q = i[r].q || []).push(arguments)
			}, i[r].l = 1 * new Date();
			a = s.createElement(o),
				m = s.getElementsByTagName(o)[0];
			a.async = 1;
			a.src = g;
			m.parentNode.insertBefore(a, m)
		})(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

		ga('create', 'UA-80489092-1', 'auto');
		ga('send', 'pageview');
	</script>
	<script type="text/javascript">
    var s = skrollr.init();
    </script>

</body>

</html>